# Generated by Django 5.1 on 2024-09-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_rename_image_produit_image_principale_produitimage'),
    ]

    operations = [
    ]
